#%RAML 0.8
title: Mod Users BL
version: v1
baseUri: http://github.com/org/folio/mod-users-bl

documentation:
    - title: Business Logic Users API
      content: A front end for mod-users, authn/credentials and auth/permissions

schemas:
    - compositeUser: !include ../schemas/compositeUser.json

/users:
    /{username}:
        get:
    /by-id:
        /{userid}:
            get:

